### ISSUE TITLE
Full Screen Window Not Showing

### ISSUE THREAD

**Issue by wifirevaithi** [dev-labs-bg/fullscreen-video-view#22]
java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
        at bg.devlabs.fullscreenvideoview.orientation.OrientationHelper.setOrientation(OrientationHelper.java:168)
        at bg.devlabs.fullscreenvideoview.orientation.OrientationHelper.toggleFullscreen(OrientationHelper.java:188)
        at bg.devlabs.fullscreenvideoview.FullscreenVideoView.toggleFullscreen(FullscreenVideoView.java:273)
        at bg.devlabs.fullscreenvideoview.VideoMediaPlayer.toggleFullScreen(VideoMediaPlayer.java:41)
        at bg.devlabs.fullscreenvideoview.VideoControllerView.doToggleFullscreen(VideoControllerView.java:389)
        at bg.devlabs.fullscreenvideoview.VideoControllerView.access$200(VideoControllerView.java:73)
        at bg.devlabs.fullscreenvideoview.VideoControllerView$2.onClick(VideoControllerView.java:102)

**Comment by slavipetrov** [comment]
Can you please provide additional information about how this bug has happened? What would you want to do exactly? The log you have provided is not clear enough to help me trace the problem.

Also, can you provide an example of the layout file where you use the FullscreenVideoView class?

**Comment by slavipetrov** [comment]
Closing this due to inactivity.
